import './globals.css'
import Header from '@/components/Header'

import { Roboto_Flex } from 'next/font/google'
import Head from 'next/head'

const roboto = Roboto_Flex({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={roboto.className}>
			<Head>
				<link rel='preload' href='/main-image.png' as='image' />
			</Head>
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
